### ISSUE TITLE
Like Filter is case sensitive

### ISSUE THREAD

**Issue by bofalke** [event-engine/php-postgres-document-store#7]
If JSONB is inside the document store the Like Filter will not work as intended since it is case sensitive. 

A structure like this:
```JSON
{
    "some": {
      "prop": "foo",
      "other": {
        "prop": "bat"
      }
    }
  },
```

can be filtered in the Document Store using the LikeFilter with this setup:
```php
new LikeFilter('some', '%FOO%')
```

But with the postgres Document store that will not work, it will only work if the value is `%foo%`

**Comment by codeliner** [comment]
thx for reporting @bofalke
